### ISSUE TITLE
Interested to know how the example could work with the implementations in separate sfdx packages.

### ISSUE THREAD

**Issue by lemmingworks** [pozil/apex-dependency-injection#1]
Hi. I read the "Breaking Runtime Dependencies" article that where you introduce this framework. Thank you for the excellent article. I just have one question.

I see how using the injector removes the compile-time dependencies, allowing the classes to be dynamically instantiated, which is great. But, seeing that the `ShippingService` interface is defined in this package, and any implementors will need access to that interface definition, I still don't see how the implementors of `ShippingService` could be defined in a different package as you mention in the article. Unless both packages have a dependency on a shared package with the `ShippingService` interface in?

**Comment by pozil** [comment]
Hi @lemmingworks, thanks for the feedback.

You got this right:
>  both packages have a dependency on a shared package with the ShippingService interface in

It's not practical for small projects but it can be handy at larger scale.

Note that there's something new in the Beta in Spring '22 that will also help with injection: `ApexTypeImplementor`
https://help.salesforce.com/s/articleView?id=release-notes.rn_apex_TypeImplementor.htm&type=5&release=236

**Comment by lemmingworks** [comment]
@pozil Thanks so much for your reply. That's was really helpful, thanks.
